### ISSUE TITLE
Unhandled exception when editing assets badly

### ISSUE THREAD

**Issue by csmith** [tsumaru720/conspectus#37]
Repro steps:

1. Create an asset
2. Edit it
3. Change the value of the 'asset class' to some random text
4. Submit the form
5. Explosion:

```
Fatal error:
Uncaught Error: Call to a member function render() on null in /home/demomoney/public_html/themes/default/theme.php:14
Stack trace:
#0 /home/demomoney/public_html/app/PageLoader.php(74): Theme->render()
#1 /home/demomoney/public_html/app/Router.php(91): PageLoader->display('asset_manager')
#2 [internal function]: Router->{closure}('74')
#3 /home/demomoney/public_html/vendor/bramus/router/src/Bramus/Router/Router.php(379): call_user_func_array(Object(Closure), Array)
#4 /home/demomoney/public_html/vendor/bramus/router/src/Bramus/Router/Router.php(361): Bramus\Router\Router->invoke(Object(Closure), Array)
#5 /home/demomoney/public_html/vendor/bramus/router/src/Bramus/Router/Router.php(287): Bramus\Router\Router->handle(Array, true)
#6 /home/demomoney/public_html/app/Router.php(17): Bramus\Router\Router->run()
#7 /home/demomoney/public_html/app/Main.php(51): Router->run()
#8 /home/demomoney/public_html/public/index.php(5): Main->__construct()
#9 {main} thrown in /home/demomoney/public_html/themes/default/theme.php on line 14
```

**Comment by csmith** [comment]
(Add new asset just says "Class not found" if you try the same there)
