### ISSUE TITLE
PHP Fatal Error when going to page that doesn't exist

### ISSUE THREAD

**Issue by ShaneMcC** [tsumaru720/conspectus#8]
Example: https://demo.money.agari.co/view/foo/bar

```

Notice: Undefined variable: dataQuery in /home/demomoney/public_html/themes/default/app/item_view.php on line 98

Fatal error: Uncaught Error: Call to a member function setFetchMode() on null in /home/demomoney/public_html/app/MySQL.php:36 Stack trace: #0 /home/demomoney/public_html/themes/default/app/item_view.php(98): MySQL->fetch(NULL) #1 /home/demomoney/public_html/app/PageLoader.php(55): Document->__construct(Object(Main), Object(Twig\Environment), Array) #2 /home/demomoney/public_html/app/Router.php(37): PageLoader->display('item_view') #3 [internal function]: Router->{closure}('foo', 'bar') #4 /home/demomoney/public_html/vendor/bramus/router/src/Bramus/Router/Router.php(379): call_user_func_array(Object(Closure), Array) #5 /home/demomoney/public_html/vendor/bramus/router/src/Bramus/Router/Router.php(361): Bramus\Router\Router->invoke(Object(Closure), Array) #6 /home/demomoney/public_html/vendor/bramus/router/src/Bramus/Router/Router.php(287): Bramus\Router\Router->handle(Array, true) #7 /home/demomoney/public_html/app/Router.php(16): Bramus\Router\Router->run() #8 /home/demomoney/public_html/app/Main.php(19): Router->run() #9 in /home/demomoney/public_html/app/MySQL.php on line 36
```

**Comment by tsumaru720** [comment]
I have no else on my type if - so i expect either "asset" or "class". It should die if anything else is given
